<?php
	$Site->titulo 		= 'AutoHemo - Controle';
	$Site->titPagina 	= 'Controle';

	$ids 	= array();
	if (!empty($data))
	{
		$vlrId = $data['0']['Retirada']['id'];
		if (!in_array($vlrId, $ids)) array_push($ids, $vlrId);
	}

	// helper
    include(APP.'View/Helper/Html.php');
    $Html = new Html();
?>
<div class='row-fluid'>
	<div class='col-md-2'><!-- esquerda -->
		<div style="text-align: center;"><!-- data -->
			<label>Data:</label>
			<?php 
				$dataC = (!empty($Site->params['data'])) ? $Site->params['data'] : date('d-m-Y');
				echo $Html->getInputData('0.Retirada.data', array('value'=>$dataC)); 
			?>
		</div>
		<div style="margin-top: 20px;">
			<?php 
				foreach($Site->ultimas as $_l => $_data) : 
				$_data = str_replace('/', '-', $_data);
			?>
			
			<?php if ($_data!=$dataC) : ?>
			<p class='pDatApli'>
				<a class='linkDatApli' href='<?= $Site->base.'controle/data:'.$_data ?>'><?= $_data ?></a></p>
			<?php else : ?>
			<p class='pDatApli' style='padding: 4px 0px 4px 0px;'><?= $dataC ?>
			<?php endif ?>
			
			<?php endforeach ?>
		</div>
	</div>

	<form name='formAplicacoes' id='formAplicacoes' method="post" action="<?= $Site->base ?>salvar_retirada">

	<div class='col-md-10'><!-- direita -->

		<div>
		<p>Este formulário tem o intuito de controlar as aplicações para Autohemoterapia, especificando a dosagem aplicada, assim como o braço que foi retirado o sangue, o que foi aplicado o sangue e a data de realização do procedimento.</p>
		</div>

		<div>
			<input type='submit' name='btSalvar' id='btSalvar' value='Salvar' class="btn btn-success" />

			<?php if (!empty($ids)) : ?>
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			<input type='button' name='btExcluir' id='btExcluir' value='Apagar' class="btn btn-danger" 
				onclick="if (window.confirm('Confirmar exclusão deste registro ?')) document.location.href='<?= $Site->base ?>
					excluir_retirada/data:<?= str_replace('/','-',$dataC) ?>/ids:<?= implode(',',$ids) ?>'" />
			<input type='button' name='btNovo' 	 id='btNovo' 	value='Nova Aplicação' class='btn btn-success' 
					onclick="document.location.href='<?= $Site->base ?>novo'" />

			<?php endif ?>

			<input type='button' name='btVoltar' id='btVoltar' value='Minhas Aplicações' class="btn btn-primary" 
				onclick='document.location.href="<?= $Site->base ?>lista"' 
				/>

		</div>

		<div>
			<h3><span>Retirada:<span><span id='totRetirada' class='soma'></span> ml</h3>
			<span>Escolha o local que foi retirado o sangue e a quantidade retirada.</span>
			<div>
				<table class='tabRetiradas'>
				<tr>

				<th class="thRetiLocal">Local</th>
				<?php foreach($Site->esquema['Retirada']['reti_qtd']['options'] as $_vlr => $_label) : ?>
					<th><center><?= $_label ?></center></th>
				<?php endforeach; ?>
				</tr>

				<?php $l = 0; ?>
				<tr>
				<td>
				<?php
					$vlrId 		= 0;
					$vlrData 	= $dataC.' '.date('H:i:s');
					$vlrUsuario = $_SESSION['Usuario']['id'];
					$vlrQtd 	= 0;
					$vlrLocal 	= 0;

					if (!empty($data))
					{
						$vlrId 		= $data['0']['Retirada']['id'];
						$vlrData 	= $data['0']['Retirada']['data'];
						$vlrUsuario	= $data['0']['Retirada']['usuario_id'];
						$vlrQtd	 	= $data['0']['Retirada']['reti_qtd'];
						$vlrLocal 	= $data['0']['Retirada']['local_id'];
						if (!in_array($vlrId, $ids)) array_push($ids, $vlrId);
					}
				?>
					<!-- id -->
					<input type='hidden' 
						value='<?= $vlrId ?>' name='data[<?= $l ?>][Retirada][id]'  class='idRetirada' />

					<select name='data[<?= $l ?>][Retirada][local_id]' class='localRetirada'>
					<?php foreach($locaisRetiradas as $_id => $_nome) : ?>
						<option value='<?= $_id ?>' 
						<?php if ($_id==$vlrLocal) echo "selected='selected'"; ?>
						>
						<?= $_nome ?></option>
					<?php endforeach ?>
					</select>

					<!-- data -->
					<input type='hidden' 
						value='<?= $vlrData ?>' name='data[<?= $l ?>][Retirada][data]' class='dataRetirada' />

					<!-- usuario -->
					<input type='hidden' value='<?= $vlrUsuario ?>' name='data[<?= $l ?>][Retirada][usuario_id]'  class='usuarioRetirada' />

				</td>
				<?php
				$c = 0;
				foreach($Site->esquema['Retirada']['reti_qtd']['options'] as $_vlr => $_label) : 
				?>
				<td align='center'>

					<!-- quantidade retirada -->
					<input type='radio' value='<?= $_vlr?>' name='data[<?= $l ?>][Retirada][reti_qtd]' id='rdRetirada<?= $l.$c ?>'
						class='rdRetirada' <?php if ($_vlr==$vlrQtd) echo "checked='checked'" ?>
					/>
				</td>
				<?php $c++; endforeach; ?>
				</tr>

				</table>
			</div>
		</div>

		<?php if (!empty($ids)) : ?>
		<div>
			<h3><span>Aplicação:<span><span id='totAplicado' class='soma'></span> ml</h3>
			<span>Escolha aonde será aplicado.</span>
			<table class='tabAplicacoes'>
				<tr>
				<th class="thApliLocal">Local</th>
				<?php foreach($Site->esquema['Aplicacao']['apli_qtd']['options'] as $_vlr => $_label) : ?>
					<th><center><?= $_label ?></center></th>
				<?php endforeach; ?>
				</tr>

				<?php 
				foreach($locais as $_l => $_arrMods) : 
				if ($_arrMods['Local']['aplicacao'])  : 
				?>

				<tr>
				<td>
					<?= $_arrMods['Local']['nome'] ?>

					<?php
						$vlrId 		= 0;
						$vlrData 	= $dataC.' '.date('H:i:s');
						$vlrUsuario = $_SESSION['Usuario']['id'];
						$vlrQtd 	= 0;
						$vlrLocal 	= 0;

						foreach($data as $_l2 => $_arrMods2)
						{
							if (isset($_arrMods2['Aplicacao']))
							{
								foreach($_arrMods2['Aplicacao'] as $_l3 => $_arrCmps3)
								{
									if ($_arrMods2['Aplicacao'][$_l3]['local_id']==$_arrMods['Local']['id'])
									{
										$vlrId 		= $_arrCmps3['id'];
										$vlrData 	= $_arrCmps3['data'];
										$vlrQtd	 	= $_arrCmps3['apli_qtd'];
										$vlrLocal 	= $_arrCmps3['local_id'];
									}
								}
							}
						}

					?>
					<!-- id -->
					<input type='hidden' 
						value='<?= $vlrId ?>'
						name='aplicacao[<?= $_l ?>][Aplicacao][id]' 
						class='idAplicacao'
					/>

					<!-- data -->
					<input type='hidden' 
						value='<?= $vlrData ?>'
						name='aplicacao[<?= $_l ?>][Aplicacao][data]' 
						class='dataAplicacao'
					/>

					<!-- local -->
					<input type='hidden' 
						value='<?= $vlrLocal ?>'
						name='aplicacao[<?= $_l ?>][Aplicacao][local_id]' 
						class='localAplicacao'
					/>

					<!-- usuario -->
					<input type='hidden' 
						value='<?= $vlrUsuario ?>'
						name='aplicacao[<?= $_l ?>][Aplicacao][usuario_id]' 
						class='usuarioAplicacao'
					/>

					<!-- local -->
					<input type='hidden' 
						value='<?= $_arrMods['Local']['id'] ?>' 
						name='aplicacao[<?= $_l ?>][Aplicacao][local_id]' 
						class='localAplicacao' 
					/>
				</td>

				<?php
					$c = 0;
					foreach($Site->esquema['Aplicacao']['apli_qtd']['options'] as $_vlr => $_label) : 
				?>
				<td align="center">
					<!-- quantidade aplicada -->
					<input type='radio' 
						value='<?= $_vlr?>' 
						name='aplicacao[<?= $_l ?>][Aplicacao][apli_qtd]' 
						id='rdAplicacao<?= $_l.$c ?>'
						class='rdAplicacao' <?php if ($_vlr==$vlrQtd) echo "checked='checked'" ?>
					/>
				</td>
				<?php $c++; endforeach; ?>
				</tr>

				<?php endif; endforeach ?>

			</table><!-- fim tabela Aplicações -->
		</div>
		<?php endif ?>

	</div>

</form>
</div>