<?php
	$Site->titulo 		= 'AutoHemo - Minhas Aplicações';
	$Site->titPagina 	= 'Minhas Aplicações';

	$Site->setHead('js','jquery.maskedinput.min');
	array_push($Site->onRead,'$("#0FiltroDataFim").mask("99/99/9999");');
	array_push($Site->onRead,'$("#0FiltroDataIni").mask("99/99/9999");');

	// helper
    include(APP.'View/Helper/Html.php');
    $Html = new Html();
?>

<div class='row-fluid'>
	<div class='menuLista col-md-2' style="border: 0px solid #ccc; min-height: 770px;"><!-- esquerda -->
	<ul>
		<li>
			<a href="<?= $Site->base ?>lista/nome:rel001">Lista Completa</a>
		</li>
	</ul>
	</div>

	<div class='cold-md-10'><!-- direita -->

		<div class='barra'><!-- barra -->
			<form name='formFiltro' id='formFiltro' method='post' action='<?= $Site->base ?>lista'>
			<?php if ($_SESSION['Usuario']['perfilId']==1) : ?>
			<?= $Html->getInput('0.Filtro.usuario_id', $filtros['usuario_id']);	?>
			<br /><br />
			<?php endif ?>

			<?= $Html->getInputData('0.Filtro.data_ini', $filtros['data_ini']);	?>
		
			<?= $Html->getInputData('0.Filtro.data_fim', $filtros['data_fim']); ?>
			<br /><br />
		
			<?= $Html->getInput('0.Filtro.retirada_id', $filtros['retirada_id']); ?>

			<?= $Html->getInput('0.Filtro.local_id', $filtros['local_id']); ?>

			<br /><br />
			<div>
				<input class='botao' type='button' name='btNovo' 	 id='btNovo' 	value='Nova Aplicação'
					onclick="document.location.href='<?= $Site->base ?>novo'" />

				<input class='botao' type='submit' name='btEnviar' id='btEnviar' value='Enviar' />

				<input class='botao' type='submit' name='btExportar' id='btExportar' value='ExportarCSV' />

				<?php if (count($data)) : ?>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span>Total de Aplicações: <?= $paginacao['tot']; ?></span>
				<?php else : ?>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span>A pesquisa retornou vazio</span>
				<?php endif ?>
				<?php 
					if ($paginacao['tot']>20) : 
					$pagA = $paginacao['pag']-1;
					$pagA = ($pagA<1) ? 1 : $pagA;

					$pagP = $paginacao['pag']+1;
					$pagP = ($pagP>$paginacao['pagU']) ? $paginacao['pagU'] : $pagP;
				?>
				<span>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<a href='<?= $Site->base ?>lista/pag:<?= $pagA ?>' title='página anterior'> << </a>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<a href='<?= $Site->base ?>lista/pag:<?= $pagP ?>' title='primeira página'> >> </a>
				</span>
				<?php endif ?>

			</div>

			</form>
		</div><!-- fim barra -->

		<div class='lista'><!-- lista -->
		<table>
		<?php if (count($data)) : ?>
		<tr>
			<th colspan='1'>#</th>
			<th>Usuário</th>
			<th>Data</th>
			<th>Local Retirada</th>
			<th>Qtd. Retirada</th>
			<th>Local Aplicado</th>
			<th>Qtd. Aplicada</th>
		</tr>
		<?php endif ?>
		<?php 
			$corr = array();
			foreach($data as $_l => $_arrMods) :
			$dtCont = $_arrMods['Aplicacao']['data'];
			$dtCont = str_replace('/','-',substr($dtCont, 0,10));
			$linkEditCont = $Site->base.'controle/data:'.$dtCont;
		?>
			<tr <?php if($_l%2==0) : ?> class='liAtiva' <?php endif; ?>>
			<td><!-- editar -->
				<a href='<?= $linkEditCont ?>'>
				<img class='btLista' id='bt<?= $_l ?>' src='<?= $Site->base ?>/img/bt_editar.png' border='0px' 
					title='Clique aqui para editar esta aplicação ...'
				/>
				</a>
			</td>
			<?php
				foreach($campos as $_l => $_cmp) : 
				$c 		= explode('.', $_cmp);
				$vlr 	= '-';
				$vlr = $_arrMods[$c['0']][$c['1']];

				if (!isset($corr[$_cmp])) $corr[$_cmp] = $_arrMods[$c['0']][$c['1']];

				if ($vlr!=$corr[$_cmp])
				{
					
				}

			?>
			<td class='td<?= ucfirst($c['0']).ucfirst($c['1']) ?>'>
				<?= $vlr ?>
			</td>
			<?php endforeach; ?>
			</tr>
		<?php endforeach ?>
		</table>
		</div><!-- fim lista -->

	</div>
</div>
