<?php
	if (isset($_SESSION['Usuario']))
	{
		$Site->setMsgFlash('O Usuário já foi autenticado !!!','msgErro');
		redirect($Site->base);
	}

	if (isset($_POST['btEnviar']))
	{
		if ($Site->autentica($_POST['data']['email'], $_POST['data']['senha']))
		{
			$Site->setMsgFlash('Usuário autenticado com sucesso ...','msgOk');
			redirect($Site->base.'/lista');
		}
	}

?>
<div class='login'>

<form name='formLogin' method='post' action='<?= $Site->base ?>login' class="form-signin" />
	<div class='linha'>
		<input type='text' name='data[email]' id='email' autofocus="autofocus" 
			autocomplete="off"
			class="email form-control"
			placeholder="e-mail"
			value=''
			/>
	</div>

	<div class='linha'>
		<input type='password' name='data[senha]' id='senha' 
			class="password form-control"
			placeholder="senha"
			value=''
			/>
	</div>

	<div class='botoes'>
	<center>
		<input type='submit' name='btEnviar' value = 'Enviar' class="btn btn-large btn-primary" />
	</center>
	</div>

</form>
</div>
<br /><br />
<div>
<center>
	<a href='<?= $Site->base ?>muda_senha'>Esqueci a senha</a>
	&nbsp;&nbsp;|&nbsp;&nbsp; <a href='<?= $Site->base ?>novo_registro'>Registre-se</a>
</center>
</div>