<?php
	$Site->titulo 		= 'AutoHemo - Meu Perfil';
	$Site->titPagina 	= 'Meu Perfil';
	$Site->setHead('js','jquery.maskedinput.min');
?>
<div class='row'>
<div class='col-md-2'></div>

<form name='formUsuario' id='formUsuario' method='post' action='<?= $Site->base ?>meu_perfil' onsubmit="return validaForm(); ">

<div class='col-md-10' style="margin: 0px 0px 20px 0px;">
	<input class='botao' type='submit' id='btSalvar' name='btSalvar' value='Salvar'  />
	<input class='botao' type='button' id='btAplicacoes' name='btAplicacoes' value='Minhas Aplicações'  
			onclick="document.location.href='<?= $Site->base ?>lista'" />
</div>

<input type='hidden' name='data[0][Usuario][id]' id='UsuarioId' value="<?= $data['0']['Usuario']['id'] ?>" />

	<div>
	<label>Nome: </label>
	<input type='text' name='data[0][Usuario][nome]' id='UsuarioNome' 
		value="<?= $data['0']['Usuario']['nome'] ?>" />
	</div>

	<div>
	<label>e-mail: </label>
	<input type='text' name='data[0][Usuario][email]' id='UsuarioEmail' 
		value="<?= $data['0']['Usuario']['email'] ?>" />
	</div>

	<div>
	<label>Telefone </label>
	<input type='text' name='data[0][Usuario][tele_resi]' id='UsuarioTeleResi' 
		value="<?= $data['0']['Usuario']['tele_resi'] ?>" />
	</div>
	<?php array_push($Site->onRead,'$("#UsuarioTeleResi").mask("(99)9999-9999");') ?>

	<div>
	<label>Celular: </label>
	<input type='text' name='data[0][Usuario][celular]' id='UsuarioCelular' 
		value="<?= $data['0']['Usuario']['celular'] ?>" />
	</div>
	<?php array_push($Site->onRead,'$("#UsuarioCelular").mask("(99)9999-9999");') ?>
	
	<div>
	<label>Aniversário: </label>
	<input type='text' name='data[0][Usuario][aniversario]' id='UsuarioAniversario' 
		value="<?= $data['0']['Usuario']['aniversario'] ?>" />
	</div>
	<?php array_push($Site->onRead,'$("#UsuarioAniversario").mask("99/99");') ?>

	<div>
	<label>Aplicador: </label>
	<select name='data[0][Usuario][aplicador]' id='UsuarioAplicador'>
		<option value='0' <?php if ($data['0']['Usuario']['aplicador']=='0') echo " selected='selected' " ?> >Não</option>
		<option value='1' <?php if ($data['0']['Usuario']['aplicador']=='1') echo " selected='selected' " ?> >Sim</option>
	</select>
	&nbsp;&nbsp; Caso concorde em ser um aplicador, o seu nome e contato serão exibidos na página de aplicadores.
	</div>

	<div>
		<label>Cidade: </label>
		<input type='hidden' name='data[0][Usuario][cidade_id]' id='UsuarioCidadeId'
			value="<?= $data['0']['Usuario']['cidade_id'] ?>" style="width: 50px; text-align: center;" />
		<input type='text' name='cidade' id='UsuarioCidade' autocomplete="off"
			value="<?= $data['0']['Cidade']['nome'].'/'.$data['0']['Cidade']['uf'] ?>" />
		<span style="font-size: 12px; margin: 0px 0px 0px 3px;">Digite o nome de sua cidade.</span>
		
		<div id="ajaxRespCidade" class="resBelTo"></div>

	</div>

	<hr>
	<div style="margin: 20px 0px 14px 0px;">
		<label>Senha: </label>
		<input type='password' name='data[0][Usuario][senha]' id='UsuarioSenha' 
			value="" />
		<span>Repita a senha: </span><input type='password' name='senha2' id='UsuarioSenha2'  value="" />
		<p style='margin: 10px 0px 0px 205px;'>
			Mantenha estes dois campos em branco para não alterar a senha.
		</p>
	</div>

	<hr>
	<div>
		<label>Perfil: </label><span style='float: left'><?= $data['0']['Perfil']['nome'] ?></span>
		<label>Ativo: </label><span style='float: left'><?= $esquema['Usuario']['ativo']['options'][$data['0']['Usuario']['ativo']] ?></span>
	</div>
	<hr>
	<div style='text-align: center;'>
		<strong>Cadastro realizado em:</strong> <?= $data['0']['Usuario']['criado'] ?>
		&nbsp;&nbsp;
		<strong>Última modificação no perfil em:</strong> <?= $data['0']['Usuario']['modificado'] ?>
	</div>

</form>
</div>
