<?php
	
?>
<div class='container novo' class='row-fluid'>
	<p>
	<center>Escolha uma data para uma nova apliação.</center>
	</p>

	<div>
		<div class='divData'>
		<center>
		<?= $Html->getInputData('0.Retirada.data', array('value'=>$dataC)); ?>
		</center>
		</div>
		<div class='divNovoBts'>
			<input class='botao' type='button' name='btCancelar' id='btCancelar' value='Cancelar' onclick="document.location.href='<?= $Site->base ?>lista'" />
			<input class='botao' type='button' name='btEditar' id='btEditar' value='Editar Aplicação' />
			<input class='botao' type='button' name='btNovo' id='btNovo' value='Criar Aplicação' />
		</div>
	</div>
	
</div>
<div id='ajaxResp'></div>
