<?php
	// helper
    include(APP.'View/Helper/Html.php');
    $Html = new Html();
?>
<div class='container novo' class='row-fluid'>
	<p>
	Escolha uma data para uma nova apliação.
	</p>

	<div>

	<?php 
		$dataC = (!empty($Site->params['data'])) ? $Site->params['data'] : date('d-m-Y');
		echo $Html->getInputData('0.Retirada.data', array('value'=>$dataC)); 
	?>
	<br />
	<div id='ajaxResp'></div>

	<br />
	<input type='button' name='btCancelar' id='btCancelar' value='Cancelar'
		class='botao' onclick="document.location.href='<?= $Site->base ?>lista'" />
	</div>
</div>
