<!DOCTYPE HTML>
<html lang="pt-br">
<head>
<title><?= $Site->titulo ?></title>
<meta charset="<?= $Site->charset ?>">

<script type="text/javascript">
var base = '<?= $Site->base?>'

</script>
	
<script type="text/javascript" src="<?= $Site->base ?>js/jquery-1.11.1.min.js"></script>
<script type="text/javascript" src="<?= $Site->base ?>js/padrao.js"></script>
<script type="text/javascript" src="<?= $Site->base ?>js/bootstrap.min.js"></script>

<script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
<script type="text/javascript" src="https://apis.google.com/js/plusone.js"></script>

<?php if (file_exists(WWW.'js/'.$Site->pagina.'.js')) : ?>
<script type="text/javascript" src="<?= $Site->base ?>js/<?= $Site->pagina ?>.js"></script>
<?php endif ?>
<?php if (isset($Site->headJs) && !empty($Site->headJs)) : foreach($Site->headJs as $_l => $_arq) : ?>
<script type="text/javascript" src="<?= $Site->base ?>js/<?= $_arq ?>.js"></script>
<?php endforeach; endif ?>

<link rel="stylesheet" type="text/css" href="<?= $Site->base ?>css/bootstrap.min.css" />
<link rel="stylesheet" type="text/css" href="<?= $Site->base ?>css/padrao.css" />
<?php if (file_exists(WWW.'css/'.$Site->pagina.'.css')) : ?>
<link rel="stylesheet" type="text/css" href="<?= $Site->base ?>css/<?= $Site->pagina ?>.css" />
<?php endif ?>
<?php if (isset($Site->headCss) && !empty($Site->headCss)) : foreach($Site->headCss as $_l => $_arq) : ?>
<link rel="stylesheet" type="text/css" href="<?= $Site->base ?>css/<?= $_arq ?>.css" />
<?php endforeach; endif ?>

<script type="text/javascript">
$(document).ready(function()
{

    <?php if (!empty($Site->msgErro)) : ?>
    $(".msg_erro").fadeOut(10000);
    <?php endif ?>

    <?php if (isset($_SESSION['msgFlash'])) : ?>
    $("#msgFlash").delay(4000).fadeOut(1000);
    <?php endif ?>

    <?php if (!empty($Site->onRead)) : foreach($Site->onRead as $_l => $_script) : ?>
    <?= $_script ?>
    <?php endforeach; endif ?>

});

</script>

<meta property="og:site_name" content="Autohemo" />
<meta property="og:title" content="<?= $Site->titulo ?>" />
<meta property="og:image" content="<?= $Site->base ?>bt_facebook.png" />

</head>

<body>
	<!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <?php //include_once(APP.'View/Elements/compartilhar.php') ?>

        <div class="container">
            <div class="navbar-header page-scroll">
                <div>
                <div style="float: left;">
                    <a class="navbar-brand" href="<?= $Site->base ?>">
                    <img src="<?= $Site->base ?>img/logo-autohemo.png"> <?= $Site->sistema ?></a>
                </div>
                <div style="margin: 17px 0px 0px 0px; float: left;">
                    <?php if (!empty($Site->titPagina)) 
                        echo '<span class="titPagina">:: '.$Site->titPagina.'</span>' 
                    ?>
                </div>
                </div>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                   
                    <?php if (isset($_SESSION['Usuario'])) : ?>
                    <li class="page-scroll">
                        <a href="<?= $Site->base ?>controle">
                        <img src="<?= $Site->base ?>img/bt_controle.png" />
                        Controle Diário
                        </a>
                    </li>
                    <li class="page-scroll">
                    <a href="<?= $Site->base ?>lista">
                        <img src="<?= $Site->base ?>img/bt_lista.png" />
                        Minhas Aplicações
                        </a>
                    </li>
                    <?php endif ?>

                    <?php if (isset($_SESSION['Usuario'])) : ?>

                    <?php if ($_SESSION['Usuario']['id']==1) : ?>
                    <li>
                    <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                        <img src="<?= $Site->base ?>img/bt_ferramentas.png" />
                        Ferramentas <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="<?= $Site->base ?>debug">SqlDump</a></li>
                            <li><a href="<?= $Site->base ?>popular">Popular Banco de Dados</a></li>
                        </ul>
                    </li>
                    </ul>
                    </li>
                    <?php endif ?>

                    <li class="page-scroll">
                    <a href="<?= $Site->base ?>meu_perfil">
                        <img src="<?= $Site->base ?>img/bt_profile.png" />
                        Meu Perfil
                    </a>
                    </li>

                    <li class="page-scroll">
                        <a href="<?= $Site->base ?>sair">
                            <img src="<?= $Site->base ?>img/bt_poweroff.png" />
                            sair
                        </a>
                    </li>
                    <?php else : ?>

                    
                    <div class="social">
                        <a href="https://www.facebook.com/sharer/sharer.php?u=www.autohemo.org" target="_blank">
                        <img src="<?= $Site->base ?>img/facebook.png"></a>

                        <a href="https://twitter.com/intent/tweet?url=www.autohemo.org&text=Auto hemoterapia é aqui&via=YOURTWITTERACCOUNTNAME" target="_blank">
                        <img src="<?= $Site->base ?>img/twitter.png"></a>

                        <a href="https://plus.google.com/share?url=www.autohemo.org" target="_blank">
                        <img src="<?= $Site->base ?>img/google_plus.png"></a>

                    </div>

                    <?php endif ?>

                </ul>
            </div>
            <!-- /.navbar-collapse -->

        </div>
        <!-- /.container-fluid -->
    </nav>

	<section>
	<?php if (isset($_SESSION['msgFlash'])) : ?>
	<div id='msgFlash'  class='<?= $_SESSION['msgFlash']['class'] ?>'>
		<?= $_SESSION['msgFlash']['texto'] ?>
		<?php unset($_SESSION['msgFlash']) ?>
	</div>
	<?php endif ?>
	</section>

    <section>
    <div class="pagina container">
		<?= $conteudo ?>

    </div>
    </section>

    <?php if (!empty($Site->msgErro)) : ?>
    <div class='containter msg_erro'>
        <h3><?= $Site->msgErro ?></h3>
    </div>
    <?php endif ?>

    <?php if (isset($_SESSION['debug'])) : ?>
    <section>
        <div class='container erros'>
            <?php include_once(APP.'View/Elements/sql_erros.php') ?>
        </div>
    </section>

    <section>
        <div class='container sqls'>
            <?php include_once(APP.'View/Elements/sql_dump.php') ?>
        </div>
    </section>
    <?php endif ?>

</body>
</html>
